### PR TITLE
Fix comparison and hashcode

### LINKED ISSUE #25: Add an implementation for GetHashCode and equality for Application
child of https://github.com/dolittle/DotNET.SDK/issues/25

### PR DESCRIPTION
**Pull request by woksin**
- Implements methods for comparison and getting hashcode in:
    - IApplication
    - IApplicationLocation
    - IApplicationStructure
    - IApplicationLocationFragment
    - IApplicationStructureFragment

- Adjusted the specs so that they work
     - Using concrete instances instead of Mocks, it proved unreliable and did not test actual functionality

fixes #25

### CODE REVIEW

File: Source/Applications/ApplicationStructureFragment.cs [hunk 1]
```diff
@@ -168,5 +172,65 @@ void ThrowIfAnyChildDoesNotBelongToType(IEnumerable<IApplicationStructureFragmen
...
+        public bool Equals(IApplicationStructureFragment other)
+        {
+            if (Type != other.Type) return false;
+            if (Recursive != other.Recursive) return false;
+            if (Required != other.Required) return false;
+            if (HasParent != other.HasParent) return false;
+
+            if (HasParent == true && other.HasParent == true) 
+            {
+                if (! Parent.Equals(other.Parent)) return false;
```
Comment (woksin) [inline Source/Applications/ApplicationStructureFragment.cs]: Hmm, we might now want to do this. This smells like infinite recursion.
Suggestions @einari ?

File: Source/Applications/ApplicationArtifactIdentifier.cs [hunk 2]
```diff
@@ -55,7 +55,7 @@ public class ApplicationArtifactIdentifier : IApplicationArtifactIdentifier
         /// <inheritdoc/>
         public bool Equals(IApplicationArtifactIdentifier other)
         {
-            if (!Location.Equals(other.Location)) return false;
+            if (Location != other.Location) return false;
 
             if (Application.Name.Value != other.Application.Name.Value) return false;
```
Comment (woksin) [inline Source/Applications/ApplicationArtifactIdentifier.cs]: This should be, Application.Equals(other.Application)
But that's scary now. Should we just stick with the Name for a while?

@einari

File: Source/Applications/ApplicationStructureFragment.cs (hunk 1 above)
Comment (woksin) [reply Source/Applications/ApplicationStructureFragment.cs]: The parent is just an representation of the Parent IApplicationStructureFragment's state at the time this ApplicationStructureFragment is constructed, therefor I don't think that the Parents can mean anything when doing comparisons.

Maybe just remove checks on Parent from Equals and GetHashCode?
@einar

File: Source/Applications/Module.cs [hunk 3]
```diff
@@ -3,56 +3,45 @@
...
     /// <summary>
     /// Represent an implementation of <see cref="IModule"/>
     /// </summary>
-    public class Module : IModule
+    public class Module : ComparableApplicationLocationSegment,
+        IModule
     {
-        List<IApplicationLocationSegment> _features = new List<IApplicationLocationSegment>();
+        /// <inheritdoc/>
+        new public ModuleName Name { get; }
```
Comment (smithmx) [inline Source/Applications/Module.cs]: Don't use new.

File: Source/Applications/Module.cs [hunk 4]
```diff
@@ -3,56 +3,45 @@
...
+using System.Linq;
 
 namespace Dolittle.Applications
 {
     /// <summary>
     /// Represent an implementation of <see cref="IModule"/>
     /// </summary>
-    public class Module : IModule
+    public class Module : ComparableApplicationLocationSegment,
+        IModule
```
Comment (smithmx) [inline Source/Applications/Module.cs]: Is there a need for a marker interface?

File: Source/Applications/Feature.cs [hunk 5]
```diff
@@ -3,55 +3,46 @@
...
+using System.Linq;
 
 namespace Dolittle.Applications
 {
     /// <summary>
     /// Represents a feature within a <see cref="Module"/>
     /// </summary>
-    public class Feature : IFeature
+    public class Feature : ComparableApplicationLocationSegment,
+        IFeature
```
Comment (smithmx) [inline Source/Applications/Feature.cs]: Why do we need the marker interface?

File: Source/Applications/NullApplicationStructure.cs [hunk 6]
```diff
@@ -12,5 +12,40 @@ public class NullApplicationStructure : IApplicationStructure
     {
         /// <inheritdoc/>
         public IApplicationStructureFragment Root => NullApplicationStructureFragment.Instance;
+
```
Comment (smithmx) [inline Source/Applications/NullApplicationStructure.cs]: Same points about CompareTo implementation and Equals.

When I have a null implementation, I tend to instantiate a single instance and make that static readonly.  You could always make the constructor private if you wanted to make sure there were no other instances instantiated.

File: Source/Applications/SubFeature.cs [hunk 7]
```diff
@@ -4,56 +4,47 @@
...
+using System.Linq;
 
 namespace Dolittle.Applications
 {
     /// <summary>
     /// Represents an implementation of <see cref="ISubFeature"/>
     /// </summary>
-    public class SubFeature : ISubFeature
+    public class SubFeature : ComparableApplicationLocationSegment,
+        ISubFeature
```
Comment (smithmx) [inline Source/Applications/SubFeature.cs]: Again a generic point - why do we need the marker interfaces?

File: Source/Applications/SubFeature.cs [hunk 8]
```diff
@@ -4,56 +4,47 @@
...
+        public SubFeature(IFeature parent, FeatureName featureName) : base(featureName)
         {
             Name = featureName;
             Parent = parent;
             parent.AddSubFeature(this);
         }
 
         /// <inheritdoc/>
-        public FeatureName Name { get; }
+        new public FeatureName Name { get; }
```
Comment (smithmx) [inline Source/Applications/SubFeature.cs]: Don't use new.

File: Specifications/Applications/for_Application/when_comparing_applications_with_different_names.cs [hunk 9]
```diff
@@ -0,0 +1,25 @@
...
+
+        Establish context = () => 
+        {
+            application_a = Application.WithName(name_a)
+                .Build();
+            application_b = Application.WithName(name_b)
+                .Build();
+        };
+
+        It should_hold_name_a = () => application_a.Name.Value.ShouldEqual(name_a);
```
Comment (smithmx) [inline Specifications/Applications/for_Application/when_comparing_applications_with_different_names.cs]: The spec is doing too much.  It says it is about comparing applications with different names, but there is no "Because of" that performs any comparison.

There should be a spec that checks the building, make sure names are assigned properly and a spec that does equality / gethashcode.

File: Specifications/Applications/for_Application/when_comparing_with_different_structures.cs [hunk 10]
```diff
@@ -0,0 +1,31 @@
...
+                .Build();
+                
+            application_b = Application.WithName(name)
+                .WithStructureStartingWith<BoundedContext>(b => b.Required
+                    .WithChild<Module>(m => m.Required))
+                .Build();
+
+            
+        };
+        It should_not_be_the_same = () => application_a.Equals(application_b).ShouldBeFalse();
```
Comment (smithmx) [inline Specifications/Applications/for_Application/when_comparing_with_different_structures.cs]: You are testing equality / gethashcode, not comparison.

I also prefer to use the Because of = () => { action } to do the actual action under test rather than just fold it into the assert.

so you should have a variable called is_equal and assigned to that in the Because and then assert against it.  Normally (and I probably would) I'd have two separate specs for equality and GetHashCode but I can see the argument for doing both actions as the setup has to be exactly the same.

File: Specifications/Applications/for_ApplicationLocation/given/different_locations.cs [hunk 11]
```diff
@@ -18,7 +18,7 @@ public class different_locations
             locationB = new ApplicationLocation(GetSegments("BoundedContext2","Module2","Feature2"));
         };
 
-        static IEnumerable<IApplicationLocationSegment> GetSegments(string boundedContextName, string moduleName, string featureName)
+        static IEnumerable<IApplicationLocationSegment> GetSegments(BoundedContextName boundedContextName, ModuleName moduleName, FeatureName featureName)
```
Comment (smithmx) [inline Specifications/Applications/for_ApplicationLocation/given/different_locations.cs]: I do like the use of the concepts here.  Much better than just a string.

File: Specifications/Applications/for_ApplicationStructureFragment/Segment.cs [hunk 12]
```diff
@@ -11,9 +12,26 @@ public Segment(string name)
         
         public IApplicationLocationSegmentName Name => throw new NotImplementedException();
 
+        public IEnumerable<IApplicationLocationSegment> Children => throw new NotImplementedException();
```
Comment (smithmx) [inline Specifications/Applications/for_ApplicationStructureFragment/Segment.cs]: This is a code smell to me.  If we can have NotImplementedException then that's an indication that our abstraction is wrong.  I think I would want to know why we need the interface.  Can we get away with a base Segment class that has default implementations?  It can be abstract and then implemented with concrete types if need be.

File: Specifications/Applications/for_BoundedContext/when_creating.cs [hunk 13]
```diff
@@ -4,11 +4,11 @@ namespace Dolittle.Applications.Specs.for_BoundedContext
...
     public class when_creating
     {
-        const string name = "Some Bounded Context";
+        static BoundedContextName name = new BoundedContextName{Value = "Some bounded context"};
         static BoundedContext bounded_context;
 
         Because of = () => bounded_context = new BoundedContext(name);
 
-        It should_have_the_name = () => ((string)bounded_context.Name).ShouldEqual(name);
+        It should_have_the_name = () => ((string)bounded_context.Name.AsString()).ShouldEqual(name.Value);
```
Comment (smithmx) [inline Specifications/Applications/for_BoundedContext/when_creating.cs]: Should just be able to equate the concepts.  So boundedContext.Name.ShouldEqual(name).  Implicits don't work with the fluent interface but you have the BoundedContextName in the variable.

File: Specifications/Applications/for_Feature/when_creating.cs [hunk 14]
```diff
@@ -16,7 +16,7 @@ public class when_creating
             feature = new Feature(module_mock.Object, name);
         };
 
-        It should_set_the_name = () => ((string) feature.Name).ShouldEqual(name);
+        It should_set_the_name = () => ((string) feature.Name).ShouldEqual(name.Value);
```
Comment (smithmx) [inline Specifications/Applications/for_Feature/when_creating.cs]: Not really part of this pull request, but I don't like the model of passing in the module to the Feature and having it add itself to the Module.  Double dispatch is ok, but not in a constructor.

**Comment by smithmx** [comment]
Actually, the only thing I would ask to change if it's not too much hassle, is the use of "new" to override the property.  However if it will delay it going out to Tomas, we can fix that later.
